# async와 await

### async 함수

`async` 키워드부터 알아봅시다. `async`는 function 앞에 위치한다.

```javascript
async function f(){
  return 1;
}
```

function 앞에 `async` 를 붙이면 해당 함수는 항상 프라미스를 반환한다. 프라미스가 아닌 값을 반환하더라도 이행 상태의 프라미스(resolved promise)로 값을 감싸 이행된 프라미스가 반환되도록 한다.



아래 예시의 함수를 호출하면 result가 1인 이행 프라미스가 반환된다. 

```javascript
async function f(){
  return 1;
}

f().then(alert); //1
```

`async` 가 붙은 함수는 반드시 프라미스를 반환하고, 프라미스가 아닌것은 프라미스로 감싸 반환한다. 



### await

```javascript
// await은 async 함수 안에서만 동작한다.
let value = await promise;
```

자바스크립트는 `await` 키워드를 만나면 프라미스가 처리 될 때 까지 기다린다. 결과는 그 이후 반환된다.

```javascript
async function f() {
	let promise = new Promise((resolve, reject)) => {
    setTimeout(() => resolve('완료!'),1000)
  });
  
  let result = await promise; // 프라미스가 이행될 때 까지 기다린다. (*)
  alert(result); // 완료
}
```



함수 호출하고,  함수 본문이 실행되는 도중 (*)로 표시한 줄에서 실행이 잠시 중단되었다가 프라미스가 처리되면 실행이 재개. 이때 프라미스 객체의 `result` 값이 변수 result에 할당된다.

`await` 은 말 그래도 프라미스가 처리될때 까지 함수 실행을 기다리게 만든다. 프라미스가 처리되면 그 결과와 함께 실행이 재기 된다. 프라미스가 처리되길 기다리는 동안 엔진이 다른일(다른 스크립트를 실행, 이벤트 처리 등)을 할 수있기에, CPU 리소스가 낭비되지 않는다.

`await`은 `promise.then`보다 좀 더 세련되게 프라미스의 ` result` 값을 얻을 수 있도록 해주는 문법이다.

`promise.then` 보다 가독성 좋고 쓰기도 쉽다.



> 일반 함수에는 `await`을 사용할 수 없다.
>
> ```javascript
> function f(){
>   let promise = Promise.resolve(1);
>   let result await promise // Syntax error
> }
> ```
>
> function 앞에 `async` 를 붙이지 않으면 이런 에러가 발생할 수 있다. `await`은 `async` 함수 안에서만 동작한다.



> `await` 은 최상위 레벨 코드에서 작동하지 않는다.
>
> `await`은 최상위 레벨코드(top-level code)에서 `await`을 사용할 수 없다. 아래와 같은 코드는 동작하지 않는다.
>
> ```javascript
> // 최상위 레벨 코드에선 문법 에러가 발생
> let response = await fetch('/article/promise-chaining/user.json');
> let user = await response.json();
> ```
>
> 하지만 익명 async 함수로 코드를 감싸면 최상위 레벨 코드에도 `await`을 사용할 수 있다.
>
> ```javascript
> (async () => {
> 	let response = await fetch('/article/promise-chaining/user.json');
>   let user = await.response.json();
>   ...
> })();
> ```



> async 클래스 메서드
>
> 메서드 이름 앞에 `async`를 추가하면 async 클래스 메서드를 선언할 수 있다.
>
> ```javascript
> class Waiter {
>   async wait(){
>     return await Promise.resolve(1);
>   }
> }
> 
> new Waiter()
> 	.wait()
> 	.then(alert); //1
> ```



### 에러 핸들링

프라미스가 정상적으로 이행되면 `await promise`는 프라미스 객체의 `result`에 저장된 값을 반환. 반면 프라미스가 거부되면 마치 `throw`문을 작성한 것처럼 에러가 던져진다.

```javascript
async function f(){
  await Promise.reject(new Error('에러 발생'));
}
```

위 코드는 아래 코드와 동일하다.

```javascript
async function f() {
	throw new Error('에러 발생!');
}
```

실제 상황에서는 프라미스가 거부 되기 전에 약간의 시간이 지체되는 경우가 있다. 이런 경우엔 `await`이 에러를 던지기 전에 지연이 발생한다.

`await`이 던진 에러는 `throw`가 던진 에러를 잡을 때 처럼 `try..catch`를 사용해 잡을 수 있다.

```javascript
async function f() {
	try{
    let response = await fetch('http://유효하지-않는-주소');
  } catch(err) {
    alert(err); // TypeError: failed to fetch
  }
}

f();
```

에러가 발생하면 제어 흐름이 `caatch` 블록으로 넘어간다. 여러 줄의 코드를 `try`로 감싸는 것도 가능하다.

```javascript
async function f() {
	try {
    let response = await fetch('https://유효하지-않는-주소');
    let user = await response.json();
  } catch(err) {
    // fetch response.json에서 발생한 에러 모두를 여기서 잡는다.
    alert(err);
  }
}

f();
```

`try..catch`가 없으면 아래 예시의 async 함수 `f()`를 호출해 만든 프라미스가 거부 상태가 된다. `f()`에 `.catch`를 추가하면 거부된 프라미스를 처리할 수 있다.

```javascript
async function f() {
  let response = await fetch('http://유효하지않는url');
}

// f()는 거부 상태의 프라미스가 된다.
f().catch(alert); // TypeError: failed to fetch
```



> **`async/await`와 `promise.then/catch`**
>
> `async/await`을 사용하면 `await`가 대기를 처리해주기 때문에 `.then`이 거의 필요하지 않다. 여기에 더해 `.catch` 대신 일반 `try..catch`를 사용할 수 있다는 장점도 생긴다. 항상 그런건 아니지만, `promise.then`을 사용하는것보다 `async/await`을 사용하는 것이 대개 더 편리하다.
>
> 하지만 문법 제약 때문에 `async`함수 바깥의 최상위 레벨 코드에서 `await`을 사용할 수 없다. 그렇기에 관행처럼 `.then/catch`를 추가해 최종결과나 처리되지 못한 에러를 다룬다.



> **`async/await` works well with `Promise.all`
>
> 여러개의 프라미스가 모두 처리되길 기다려야 하는 상황이면 이 프라미스들을 `Promise.all`로 감싸고 여기에 `await`을 붙여 사용할 수 있다.
>
> ```javascript
> // 프라미스 처리 결과가 담긴 배열을 기다린다.
> let results = await.Promise.all([
>   fetch(url1),
>   fetch(url2),
>   ...
> ]);
> ```
>
> 실패한 프라미스에서 발생한 에러는 보통 에러와 마찬가지로 `Promise.all`로 전파된다. 에러 때문에 생긴 예외는 `tryt..catch`로 감싸 잡을 수 있다.